/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_graphchi_util_Sorting */

#ifndef _Included_edu_cmu_graphchi_util_Sorting
#define _Included_edu_cmu_graphchi_util_Sorting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_cmu_graphchi_util_Sorting
 * Method:    quickSort
 * Signature: ([J[III)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_graphchi_util_Sorting_quickSort
  (JNIEnv *, jclass, jlongArray, jintArray);

JNIEXPORT jintArray JNICALL Java_edu_cmu_graphchi_util_Sorting_quickSortWithIndex
    (JNIEnv *, jclass, jlongArray);
    
#ifdef __cplusplus
}
#endif
#endif
